### ISSUE TITLE
Is random Bits transmission possible?

### ISSUE THREAD

**Issue by Suvi-dha** [yoniLc/DDECC#1]
Hi, 

I may sound lame from the question I asked but please allow me to give a context. So, I am not from communications background. Just a pure Computer Vision researcher. I have recently come across a problem where I need to transfer random bit string over a network and recover the same with zero loss. I experimented with a linear autoencoder architecture with one linear layer each and of course I could recover the string with almost zero loss. But the problems can't be so simple, right? Now when I tried to add noise to my data after encoding step; my decoder isn't able to recover the string due to obvious non-linearity induced in between the network. 

Then I read more and came across communications field and could relate this with my problem statement because that's what I am trying to do -> just transmitting information bits and trying to recover it with ECC embedded. 

I came across your work and trying to understand if this is it what I am looking for. But when I checked your dataset (POLAR); I found they're some kind of vector matrices with ones and zeros extending upto a length like [000011111110000], meaning no mixed bits like [01010000111010100110011]. 

So; please help me understand if such random bit strings are possible to recover and whether I am on the right path?

Thanks a lot for this work!

**Comment by yoniLc** [comment]
Hi,

The goal is to remain robust to (channel) noise by adding redundant information (bits).
You can have a look here: https://en.wikipedia.org/wiki/Generator_matrix

So, in your case, you should choose a code (plenty of codes) of the desired length (# of bits) and rate (~# of redundant bits) and train the DDECC (or [ECCT](https://github.com/yoniLc/ECCT)) on it.

Regarding the mixing, you can use the `standard_form` flag in the code creation function to extract the (former) information bits. (You can also perform Gaussian elimination over GF2, but it is more advanced).

**Comment by Suvi-dha** [comment]
Thanks a lot! I'll look into your suggestions.
